# Generated by Django 6.0.5 on 2026-06-02 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_category_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='updted_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
