# Generated by Django 6.0.5 on 2026-06-03 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_category_updted_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='updted_at',
            new_name='updated_at',
        ),
    ]
