# Generated by Django 6.0.5 on 2026-06-06 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_variantimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productvariant',
            name='image',
        ),
    ]
