# Generated by Django 6.0.5 on 2026-06-07 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_remove_productvariant_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariant',
            name='size',
            field=models.PositiveIntegerField(),
        ),
    ]
