# Generated by Django 6.0.5 on 2026-06-21 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('cod', 'Cash on Delivery'), ('card', 'Credit Card'), ('upi', 'UPI Transfer')], default='cod', max_length=20),
        ),
    ]
