# Generated by Django 6.0.5 on 2026-05-28 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_otp_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otp',
            name='user',
        ),
    ]
