# Generated by Django 6.0.5 on 2026-07-14 15:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0011_orderitem_return_reason_alter_orderitem_status"),
        ("userprofile", "0002_wallettransaction"),
    ]

    operations = [
        migrations.AddField(
            model_name="wallettransaction",
            name="order_item",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="wallet_transactions",
                to="orders.orderitem",
            ),
        ),
    ]
